import { access, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import prettier from "prettier";
import type { Action, Goal, Step } from "@lookout/types";
import type { StoreWithRoot } from "@lookout/store";

export type EmitSpecInput = {
  goal: Goal;
  steps: Step[];
  auth: {
    type: "none" | "credentials" | "storageState";
    loginUrl?: string;
    usernameSelector?: string;
    passwordSelector?: string;
    submitSelector?: string;
    storageStatePath?: string;
  };
  runMeta: {
    runId: string;
    lookoutVersion: string;
    generatedAt: string;
  };
};

export type EmittedFile = {
  goalId: string;
  path: string;
  action: "written" | "skipped-existing-newer" | "overwritten";
};

/**
 * Roles that Playwright's fill() can operate on without throwing at runtime.
 * Anything outside this list (e.g. button, link) should fall back to a TODO
 * comment rather than emit a spec that will fail the first time it runs.
 */
const FILLABLE_ROLES = new Set([
  "textbox",
  "searchbox",
  "combobox",
  "spinbutton",
]);

function selectorLooksFillable(selector: string): boolean {
  const m = selector.match(/getByRole\(\s*["'](\w+)["']/);
  // non-role locators (getByTestId, css, etc.) are ambiguous — allow
  if (!m) return true;
  const role = m[1];
  if (role === undefined) return true;
  return FILLABLE_ROLES.has(role);
}

function emitStepLine(action: Action, selector: string | null): string {
  if (action.kind === "navigate") {
    return `await page.goto(${JSON.stringify(action.url)});`;
  }
  if (action.kind === "wait") {
    return `await page.waitForTimeout(${action.ms});`;
  }
  if (action.kind === "assert") {
    if (action.expectation.includes("/") && !action.expectation.includes(" ")) {
      return `await expect(page).toHaveURL(new RegExp(${JSON.stringify(action.expectation)}));`;
    }
    return `await expect(page.locator("body")).toContainText(${JSON.stringify(action.expectation)});`;
  }
  if (!selector) {
    return `// TODO: step skipped — no stable selector`;
  }
  if (action.kind === "click") return `await ${selector}.click();`;
  if (action.kind === "fill") {
    if (!selectorLooksFillable(selector)) {
      return `// TODO: step skipped — resolved selector ${selector} is not a fillable role`;
    }
    return `await ${selector}.fill(${JSON.stringify(action.value)});`;
  }
  if (action.kind === "select") return `await ${selector}.selectOption(${JSON.stringify(action.value)});`;
  return `// TODO: unsupported action`;
}

/**
 * Emit a formatted Playwright test source for a completed goal.
 */
export async function emitSpec(input: EmitSpecInput): Promise<string> {
  const header = `// Generated by Lookout v${input.runMeta.lookoutVersion} on ${input.runMeta.generatedAt}.
// Source: run ${input.runMeta.runId}, goal ${input.goal.id} "${input.goal.prompt}"
//
// Regenerating this file with \`lookout generate-tests\` will overwrite these contents.
`;

  const imports = `import { test, expect } from "@playwright/test";\n`;

  let useBlock = "";
  if (input.auth.type === "storageState" && input.auth.storageStatePath) {
    useBlock = `test.use({ storageState: ${JSON.stringify(input.auth.storageStatePath)} });\n\n`;
  }

  let authBlock = "";
  if (input.auth.type === "credentials" && input.auth.loginUrl) {
    authBlock = `
  await page.goto(${JSON.stringify(input.auth.loginUrl)});
  await page.locator(${JSON.stringify(input.auth.usernameSelector)}).fill(process.env.LOOKOUT_USER!);
  await page.locator(${JSON.stringify(input.auth.passwordSelector)}).fill(process.env.LOOKOUT_PASS!);
  await page.locator(${JSON.stringify(input.auth.submitSelector)}).click();
`;
  }

  const body = input.steps
    .filter((s) => s.action.kind !== "complete" && s.action.kind !== "stuck")
    .map((s) => {
      if (s.verdict !== "ok") {
        return `  // TODO: step ${s.idx} skipped — verdict=${s.verdict}`;
      }
      // navigate/assert/wait don't need a resolved selector; only skip
      // selector-dependent actions when no selector was resolved.
      const needsSelector =
        s.action.kind === "click" || s.action.kind === "fill" || s.action.kind === "select";
      if (needsSelector && !s.selectorResolved) {
        return `  // TODO: step ${s.idx} skipped — no stable selector`;
      }
      return `  ${emitStepLine(s.action, s.selectorResolved)}`;
    })
    .join("\n");

  const raw = `${header}\n${imports}${useBlock}test(${JSON.stringify(input.goal.prompt)}, async ({ page }) => {\n${authBlock}\n${body}\n});\n`;
  return await prettier.format(raw, { parser: "typescript" });
}

/**
 * Emit Playwright specs for all completed goals in a run.
 */
export async function emitAll(opts: {
  store: StoreWithRoot;
  runId: string;
  outDir: string;
  force?: boolean | undefined;
  auth: EmitSpecInput["auth"];
  version?: string | undefined;
}): Promise<EmittedFile[]> {
  await mkdir(opts.outDir, { recursive: true });
  const goals = await opts.store.listGoalsForRun(opts.runId);
  const out: EmittedFile[] = [];
  const version = opts.version ?? "0.5.0";
  const generatedAt = new Date().toISOString();
  for (const g of goals) {
    if (g.status !== "complete") continue;
    const steps = await opts.store.listStepsForGoal(g.id);
    const filePath = path.join(opts.outDir, `${g.id}.spec.ts`);
    // Detect whether the target exists up-front so we can honor the
    // --force flag and report exactly what happened. Previously every
    // file was labelled "written" — overwrites were invisible.
    let existed = false;
    try {
      await access(filePath);
      existed = true;
    } catch {
      // doesn't exist — will be "written"
    }
    if (existed && !opts.force) {
      out.push({ goalId: g.id, path: filePath, action: "skipped-existing-newer" });
      continue;
    }
    const source = await emitSpec({
      goal: g,
      steps,
      auth: opts.auth,
      runMeta: { runId: opts.runId, lookoutVersion: version, generatedAt },
    });
    await writeFile(filePath, source, "utf8");
    out.push({
      goalId: g.id,
      path: filePath,
      action: existed ? "overwritten" : "written",
    });
  }
  return out;
}
